# Generated by Django 4.1.1 on 2022-09-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_stars_post_type_alter_post_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nickname', models.CharField(max_length=15)),
                ('commentary', models.TextField()),
                ('username', models.CharField(max_length=30)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('stars', models.IntegerField(null=True)),
            ],
        ),
    ]
